inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - bin/*
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - table_sync.gemspec

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method
