language: ruby

rvm: 
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

sudo: false

dist: xenial

cache: bundler

services:
  - postgresql

addons:
  postgresql: "10"

before_install: gem install bundler

before_script:
  - psql -c 'create database table_sync_test;' -U postgres

script:
  - bundle exec rake bundle:audit
  - bundle exec rubocop
  - bundle exec rspec
